redis:
  url: ${REDIS_URL}
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
scripts:
  path:
    token_bucket: /scripts/token_bucket.lua 
    sliding_window: /scripts/sliding_window.lua
    fixed_window: /scripts/sliding_window.lua
ratelimiter:
  strategy: token_bucket